In [15]:
#Importing necessary Libraries
import pandas as pd

In [3]:
# Loading the dataset
file_path= "../Data/Loan_acc_prediction_FCS_exercise.xlsx"
loan_df = pd.read_excel(file_path, sheet_name="Loan Demographics")
comm_df = pd.read_excel(file_path, sheet_name="Communication Activity")

In [6]:
# Initial Inspection of Loan Demographics
print("SHAPE")
print(loan_df.shape)

print("\nINFO")
loan_df.info()

print("\nSAMPLE DATA")
display(loan_df.head(10))

SHAPE
(154849, 22)

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154849 entries, 0 to 154848
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Loan Id             154849 non-null  int64
 1   clnt_no             154849 non-null  object
 2   original_balance    154849 non-null  float64
 3   current_balance     154849 non-null  float64
 4   last_pmt_amt        154849 non-null  float64
 5   last_pmt_date       457 non-null     datetime64[ns]
 6   birthday            154849 non-null  datetime64[ns]
 7   status              154849 non-null  int64
 8   lastNoticeSent      154849 non-null  datetime64[ns]
 9   state               154167 non-null  object
 10  Creditor name       154849 non-null  object
 11  times_dials         154849 non-null  int64
 12  times_connect       154849 non-null  int64
 13  times_contact       154849 non-null  int64
 14  times_rpc           154849 non-null  int64
 15  times_ptp           154849 non-null  int64
 16  times_up            154849 non-null  int64
 17  times_drop          154849 non-null  int64
 18  times_lm            154849 non-null  int64
 19  total_portal_visit  154849 non-null  int64
 20  chargeoff_date      154849 non-null  datetime64[ns]
 21  Payment_Next30Days  154849 non-null  int64
dtypes: datetime64[ns](4), float64(3), int64(12), object(3)
memory usage: 26.0+ MB

SAMPLE DATA

,Loan Id,clnt_no,original_balance,current_balance,last_pmt_amt,last_pmt_date,birthday,status,lastNoticeSent,state,...,times_connect,times_contact,times_rpc,times_ptp,times_up,times_drop,times_lm,total_portal_visit,chargeoff_date,Payment_Next30Days
0,10113,GALOM1,1070.18,1070.18,0.0,NaT,1988-03-02,79,2024-02-27,OH,...,0,0,0,0,0,0,0,0,2015-06-26,0
1,10121,GALOM1,2358.76,2358.76,0.0,NaT,1981-10-15,29,2022-09-14,AZ,...,0,0,0,0,0,0,0,0,2018-11-12,0
2,10122,GAL102,922.58,922.58,0.0,NaT,1994-06-16,89,2024-12-16,TN,...,0,0,0,0,0,0,0,0,2021-07-26,0
3,10125,GALM12,1026.16,1026.16,0.0,NaT,1993-05-25,89,2022-06-02,CA,...,0,0,0,0,0,0,0,0,2022-04-27,0
4,10127,GALM12,1284.37,1284.37,0.0,NaT,1981-04-02,52,2025-01-27,NJ,...,0,0,0,0,0,0,0,0,2022-06-17,0
5,10131,GAL102,2316.93,2316.93,0.0,NaT,1977-08-25,89,2024-11-22,RI,...,0,0,0,0,0,0,0,0,2021-10-08,0
6,10132,GALM12,3314.43,3314.43,0.0,NaT,1988-05-23,88,2025-09-11,ME,...,0,0,0,0,0,0,0,0,2023-02-05,0
7,10135,GALO11,2859.85,2859.85,0.0,NaT,1948-02-01,18,2024-09-17,KS,...,0,0,0,0,0,0,0,0,2008-03-31,0
8,10142,RCS001,882.01,702.01,30.0,2025-08-05,1957-02-11,18,2025-07-28,OR,...,0,0,0,0,0,0,0,0,2023-10-15,1
9,10147,GAL102,1003.20,1003.20,0.0,NaT,1972-05-08,89,2024-11-22,IN,...,0,0,0,0,0,0,0,0,2020-08-19,0

In [7]:
print("MISSING VALUES")
print(loan_df.isnull().sum())

MISSING VALUES
Loan Id                    0
clnt_no                    0
original_balance           0
current_balance            0
last_pmt_amt               0
last_pmt_date         154392
birthday                   0
status                     0
lastNoticeSent             0
state                    682
Creditor name              0
times_dials                0
times_connect              0
times_contact              0
times_rpc                  0
times_ptp                  0
times_up                   0
times_drop                 0
times_lm                   0
total_portal_visit         0
chargeoff_date             0
Payment_Next30Days         0
dtype: int64

In [8]:
#Check for the Binary nature of the Target Variable
loan_df['Payment_Next30Days'].unique()

array([0, 1])

In [9]:
# Check for duplication 
print("Duplicate Rows:")
print(loan_df.duplicated().sum())

# Check for duplication at granularity level
print("\nDuplicate Loan IDs:")
print(loan_df['Loan Id'].duplicated().sum())

Duplicate Rows:
0

Duplicate Loan IDs:
0

In [10]:
# Percentage of missing values
(loan_df.isnull().mean() * 100).sort_values(ascending=False)

last_pmt_date         99.704874
state                  0.440429
clnt_no                0.000000
original_balance       0.000000
current_balance        0.000000
Loan Id                0.000000
last_pmt_amt           0.000000
birthday               0.000000
status                 0.000000
lastNoticeSent         0.000000
Creditor name          0.000000
times_dials            0.000000
times_connect          0.000000
times_contact          0.000000
times_rpc              0.000000
times_ptp              0.000000
times_up               0.000000
times_drop             0.000000
times_lm               0.000000
total_portal_visit     0.000000
chargeoff_date         0.000000
Payment_Next30Days     0.000000
dtype: float64

## Initial Observations

- Dataset contains ~155k loan/account level records with 22 features
- Target variable has been identified to be `Payment_Next30Days`, indicating a binary classification problem
- Behavioral collection variables are present (`times_dials`, `times_contact`, `times_ptp`, etc.)
- Financial variables such as `balances` and `payment amounts` are available
- Date columns are already parsed into datetime format
- `last_pmt_date` contains extremely high missingness
- Minor missingness observed in `state`

In [11]:
# Initial Inspection of Communication Activity
print("SHAPE")
print(comm_df.shape)

print("\nINFO")
comm_df.info()

print("\nSAMPLE DATA")
display(comm_df.head(10))

SHAPE
(115560, 3)

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115560 entries, 0 to 115559
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Loan Id     115560 non-null  int64
 1   Event Type  115560 non-null  object
 2   Timestamp   115560 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 2.6+ MB

SAMPLE DATA

   Loan Id       Event Type               Timestamp
0    10188    SMS Delivered 2024-12-23 00:44:56.574
1    10188  Email Delivered 2025-01-10 02:38:08.574
2    10188       Email Sent 2025-01-16 18:24:33.574
3    10188         SMS Sent 2025-08-04 18:26:43.574
4    10231       Email Sent 2024-10-29 19:58:40.000
5    10231       Email Sent 2025-04-30 17:41:41.574
6    10240  Email Delivered 2024-11-28 15:53:10.574
7    10240       Email Sent 2025-03-18 08:39:36.574
8    10240       Email Sent 2025-04-29 12:22:55.574
9    10446    SMS Delivered 2024-11-12 08:11:01.574

In [12]:
print("MISSING VALUES")
print(comm_df.isnull().sum())

MISSING VALUES
Loan Id       0
Event Type    0
Timestamp     0
dtype: int64

In [13]:
# Check for duplication 
comm_df.duplicated().sum()

np.int64(0)

In [14]:
# Check Event types
comm_df['Event Type'].value_counts()

Event Type
SMS Sent           34159
SMS Delivered      32150
Email Sent         25525
Email Delivered    20280
Email Read          3446
Name: count, dtype: int64

## Communication Activity Observations

- Communication dataset contains ~115k event-level records
- Each row represents a timestamped communication event linked to a loan/account
- Multiple communication channels observed, including SMS and email interactions
- Dataset contains no missing values
- Presence of timestamps enables future recency and frequency feature engineering
- Event-level data will likely require aggregation before model training
- Temporal leakage considerations will be important during feature construction